version: '3'
services:
  webserver:
    build:
      context: .
    container_name: "PHP-APACHE-SUDOKU"
    ports:
      - "8000:80"
    links:
      - database
    volumes:
      - ./:/var/www/html:rw
      - .apache.conf:/etc/apache2/sites-enabled
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html
      PMA_PORT: 8080
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      HOST_MACHINE_MYSQL_PORT: 3306
      XDEBUG_CONFIG: "client_host=host.docker.internal remote_port=9003"
  database:
    image: mysql:8
    container_name: "MYSQL-8-SUDOKU"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
  phpmyadmin:
    image: phpmyadmin
    container_name: "PHPMYADMIN-SUDOKU"
    links:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:80"
      - "443:443"
